apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: nodejs-nestjs
    namespace: app
    envs:
      - ".env"
    type: Opaque
configMapGenerator:
  - name: nodejs-nestjs
    envs:
    - .env

generatorOptions:
  disableNameSuffixHash: true