apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-fiber
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: deployment/argo-config/go-fiber
    repoURL: git@github.com:iamlookod/devops.git