apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-nestjs-app
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: plugins/kustomized-helm
    repoURL: git@github.com:iamlookod/devops.git
    targetRevision: main