apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-nestjs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/iamlookod/devops.git
    targetRevision: main
    path: deployment/argo-config/nodejs-nestjs
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
