apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-nestjs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:iamlookod/devops.git
    targetRevision: main
    path: deployment/argo-config/nodejs-nestjs
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app

