apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-nestjs-app
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment/argo-config/nodejs-nestjs
    repoURL: git@github.com:iamlookod/devops.git
    targetRevision: main
    plugin:
      name: kustomized-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
