apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-fastapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:iamlookod/devops.git
    targetRevision: main
    path: deployment/argo-config/python-fastapi
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app
