# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

resources:
  - ./all.yaml

secretGenerator:
  - name: python-fastapi
    namespace: app
    envs:
      - "config/secrets.env"
    type: Opaque
configMapGenerator:
  - name: python-fastapi
    envs:
      - "config/configmap.env"

generatorOptions:
  disableNameSuffixHash: true