apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.6.5
    helm:
      releaseName: loki-stack
      values: |
        loki:
          enabled: true
        promtail:
          enabled: true
        fluent-bit:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
