apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-nestjs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/iamlookod/devops.git
    targetRevision: main
    path: deployment/nodejs-nestjs
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app
