apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.name }}-app"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: "deployment/argo-config/{{ .Values.name }}"
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}