apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.name }}-config"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: "deployment/argo-config/{{ .Values.name }}/config"
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}